---
- name: Build fabric configuration
  hosts: REGION1, REGION2, Internet
  tasks:
    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
