custom_hostname: Edge14
custom_ethernet_interfaces:
  - name: Ethernet1
    flow_tracker:
      hardware: FLOW-TRACKER
    peer: H14
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 172.16.14.254/24
