custom_hostname: Edge24
custom_ethernet_interfaces:
  - name: Ethernet1
    flow_tracker:
      hardware: FLOW-TRACKER
    peer: H24
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 172.16.24.254/24
