hostname: Edge12
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback10
  description: Edge-12_lo10
  shutdown: false
  ip_address: 192.168.0.12/32
ethernet_interfaces:
- name: Ethernet1
  vrf: VRF_A
  peer: Leaf12
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.32.1/24
  ospf_area: 0
  ospf_network_point_to_point: true
- name: Ethernet2
  peer: R1-PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.15.1/24
- name: Ethernet3
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.16.1/24
- name: Ethernet4
  peer: Leaf11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.31.1/24
  ospf_area: 0
  ospf_network_point_to_point: true
router_bgp:
  as: 65000
  router_id: 192.168.0.12
  neighbors:
    - ip_address: 192.12.15.2
      remote_as:  65102
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.12.16.2
      remote_as:  65103
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.12.15.2
        activate: true
      - ip_address: 192.12.16.2
        activate: true
      # - ip_address:  192.12.32.2
      #   activate: true  
    networks: 
      - prefix: 192.168.0.12/32
      - prefix: 172.16.12.0/24
  redistribute_routes:
    - source_protocol: connected
  vrfs:
    - name: VRF_A
      redistribute_routes:
        - source_protocol: ospf
        - source_protocol: connected

router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.10
      vrf: VRF_A
      redistribute:
        bgp: