hostname: P20
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Region2_P20_lo10
  shutdown: false
  ip_address: 192.168.0.53/32
ethernet_interfaces:
- name: Ethernet1
  peer: P21
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.53.54.1/24
- name: Ethernet2
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.53.2/24
- name: Ethernet3
  peer: ISP-2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.26.53.2/24
- name: Ethernet4
  peer: PE3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.53.83.1/24
- name: Ethernet5
  peer: PE4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.53.84.1/24
- name: Ethernet6
  peer: ISP-3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.53.75.1/24
- name: Ethernet7
  peer: Edge24
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.24.53.2/24
router_bgp:
  as: 65000
  router_id: 192.168.0.53
  peer_groups:
    - name: CORE
      remote_as: 65001
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - name: ISP-3
      remote_as: 65002
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  neighbors:
    - ip_address: 192.53.83.2
      peer_group: CORE
    - ip_address: 192.53.84.2
      peer_group: CORE
    - ip_address: 192.53.75.2
      peer_group: ISP-3
    - ip_address: 192.26.53.1
      remote_as:  65203
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.25.53.1
      remote_as:  65202
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.26.53.1
        activate: true
      - ip_address: 192.25.53.1
        activate: true
    peer_groups:
      - name: CORE
        activate: true
      - name: ISP-3
        activate: true
    networks:
      - prefix: 192.168.0.53/32
    redistribute_routes:
    - source_protocol: connected
